# GitHub: https://github.com/behdadaliz/Lixet.git | Author: behdadaliz
"""Isolated service inspector tests."""

from __future__ import annotations

import tempfile
import unittest
from pathlib import Path

from services.dns_service import DNSService
from services.fstab_service import FstabService
from services.nginx_service import NginxService
from services.ssh_service import SSHService
from services.sudoers_service import SudoersService
from services.sysctl_service import SysctlService
from services.systemd_service import SystemdService
from services.ufw_service import UFWService
from tests.helpers import FakeRunner


class SSHServiceTests(unittest.TestCase):
    def test_reads_includes_in_lexical_order(self) -> None:
        with tempfile.TemporaryDirectory() as tmp:
            root = Path(tmp)
            includes = root / "sshd_config.d"
            includes.mkdir()
            (root / "sshd_config").write_bytes(b"Include sshd_config.d/*.conf\n")
            (includes / "20-second.conf").write_bytes(b"Port 2222\n")
            (includes / "10-first.conf").write_bytes(b"PasswordAuthentication no\n")
            data = SSHService(str(root / "sshd_config"), FakeRunner()).inspect()
            self.assertEqual(
                [Path(item["file_path"]).name for item in data["files"]],
                ["sshd_config", "10-first.conf", "20-second.conf"],
            )
            self.assertFalse(data["include_errors"])
            self.assertEqual(
                [row["directive"] for row in data["lines"] if row["directive"]],
                ["Include", "PasswordAuthentication", "Port"],
            )

    def test_include_cycle_is_reported_and_bounded(self) -> None:
        with tempfile.TemporaryDirectory() as tmp:
            root = Path(tmp)
            (root / "sshd_config").write_bytes(b"Include loop.conf\n")
            (root / "loop.conf").write_bytes(b"Include sshd_config\n")
            data = SSHService(str(root / "sshd_config"), FakeRunner()).inspect()
            self.assertTrue(any("cycle" in message.lower() for message in data["include_errors"]))
            self.assertEqual(len(data["files"]), 2)


class NginxServiceTests(unittest.TestCase):
    def test_reads_exact_included_files(self) -> None:
        with tempfile.TemporaryDirectory() as tmp:
            root = Path(tmp)
            conf = root / "conf.d"
            conf.mkdir()
            (root / "nginx.conf").write_bytes(b"events {}\nhttp {\ninclude conf.d/*.conf;\n}\n")
            (conf / "site.conf").write_bytes(b"server { listen 80; }\n")
            data = NginxService(str(root / "nginx.conf"), FakeRunner()).inspect()
            self.assertEqual([Path(item["file_path"]).name for item in data["files"]], ["nginx.conf", "site.conf"])
            self.assertFalse(data["include_errors"])

    def test_include_cycle_is_reported(self) -> None:
        with tempfile.TemporaryDirectory() as tmp:
            root = Path(tmp)
            (root / "nginx.conf").write_bytes(b"events {}\ninclude loop.conf;\n")
            (root / "loop.conf").write_bytes(b"include nginx.conf;\n")
            data = NginxService(str(root / "nginx.conf"), FakeRunner()).inspect()
            self.assertTrue(any("cycle" in message.lower() for message in data["include_errors"]))


class OtherServiceTests(unittest.TestCase):
    def test_dns_detects_networkmanager_without_external_lookup(self) -> None:
        with tempfile.TemporaryDirectory() as tmp:
            path = Path(tmp) / "resolv.conf"
            path.write_bytes(b"# Generated by NetworkManager\nnameserver 127.0.0.53\n")
            runner = FakeRunner()
            data = DNSService(str(path), runner).inspect()
            self.assertEqual(data["resolver_manager"], "NetworkManager")
            self.assertFalse(any(call[:2] == ("getent", "hosts") for call in runner.calls))

    def test_ufw_reads_state_and_defaults_from_correct_files(self) -> None:
        with tempfile.TemporaryDirectory() as tmp:
            etc = Path(tmp) / "etc"
            (etc / "ufw").mkdir(parents=True)
            (etc / "default").mkdir()
            state = etc / "ufw" / "ufw.conf"
            state.write_bytes(b"ENABLED=yes\n")
            (etc / "default" / "ufw").write_bytes(b'IPV6=yes\nDEFAULT_INPUT_POLICY="DROP"\n')
            data = UFWService(str(state), FakeRunner()).inspect()
            self.assertEqual(
                [(item["role"], Path(item["file_path"]).name) for item in data["files"]],
                [("state", "ufw.conf"), ("defaults", "ufw")],
            )

    def test_systemd_runtime_runs_without_local_unit_directory(self) -> None:
        with tempfile.TemporaryDirectory() as tmp:
            runner = FakeRunner()
            data = SystemdService(str(Path(tmp) / "missing"), runner).inspect()
            self.assertTrue(data["config_absent"])
            self.assertEqual(data["units"], [])
            self.assertIn(("systemctl", "--failed", "--no-pager", "--plain"), runner.calls)
            self.assertIn(("systemctl", "is-system-running"), runner.calls)

    def test_systemd_reads_dropins_after_main_unit(self) -> None:
        with tempfile.TemporaryDirectory() as tmp:
            root = Path(tmp)
            unit = root / "demo.service"
            unit.write_bytes(b"[Service]\nExecStart=/bin/true\n")
            dropins = root / "demo.service.d"
            dropins.mkdir()
            (dropins / "10-override.conf").write_bytes(b"[Service]\nRestart=on-failure\n")
            data = SystemdService(str(root), FakeRunner()).inspect()
            self.assertEqual(
                [Path(item["file_path"]).name for item in data["units"][0]["files"]],
                ["demo.service", "10-override.conf"],
            )

    def test_sudoers_d_ignores_names_with_dot_or_tilde(self) -> None:
        with tempfile.TemporaryDirectory() as tmp:
            etc = Path(tmp)
            main = etc / "sudoers"
            main.write_bytes(b"root ALL=(ALL) ALL\n")
            directory = etc / "sudoers.d"
            directory.mkdir()
            (directory / "valid").write_bytes(b"user ALL=(ALL) /bin/true\n")
            (directory / "ignored.conf").write_bytes(b"bad\n")
            (directory / "ignored~").write_bytes(b"bad\n")
            data = SudoersService(str(main), FakeRunner()).inspect()
            self.assertEqual([Path(item["file_path"]).name for item in data["files"]], ["sudoers", "valid"])

    def test_fstab_uses_explicit_tab_file(self) -> None:
        with tempfile.TemporaryDirectory() as tmp:
            path = Path(tmp) / "fstab"
            path.write_bytes(b"")
            runner = FakeRunner()
            FstabService(str(path), runner).inspect()
            self.assertIn(("findmnt", "--verify", "--tab-file", str(path)), runner.calls)

    def test_sysctl_uses_directory_precedence_then_filename_order(self) -> None:
        with tempfile.TemporaryDirectory() as tmp:
            root = Path(tmp)
            for relative in ("etc/sysctl.d", "run/sysctl.d", "usr/lib/sysctl.d"):
                (root / relative).mkdir(parents=True)
            (root / "usr/lib/sysctl.d/10-vendor.conf").write_bytes(b"vm.swappiness=60\n")
            (root / "run/sysctl.d/50-shared.conf").write_bytes(b"vm.swappiness=30\n")
            (root / "etc/sysctl.d/50-shared.conf").write_bytes(b"vm.swappiness=20\n")
            (root / "etc/sysctl.conf").write_bytes(b"vm.swappiness=10\n")
            data = SysctlService(str(root / "etc/sysctl.conf")).inspect()
            names = [Path(item["file_path"]).name for item in data["files"]]
            self.assertEqual(names, ["10-vendor.conf", "50-shared.conf", "sysctl.conf"])
            shared = next(item for item in data["files"] if Path(item["file_path"]).name == "50-shared.conf")
            self.assertIn("etc", Path(shared["file_path"]).parts)


if __name__ == "__main__":
    unittest.main()
